dependencies:
- graphviz
- pip:
    - dataclasses
    - mistletoe
    - notebook
    - ipython
    - nbconvert
    - hypothesis
    - graphviz
    - importnb
    - tox
    - toolz
    - git+https://github.com/nteract/vdom@master
    # - vdom
