dependencies:
- graphviz
- ipywidgets
- pandas
- matplotlib

- pip:
  - ipython>7
  - nbconvert
  - importnb
  - ruamel.yaml
  - jupyter_client
  - htmlminify
  - xonsh

  - hypothesis
  - importnb
  - tox
  - nbval
  - nbsphinx
  - nikola
  - gitpython
  - sympy
  - pytest
  - black
  - isort
